### ISSUE TITLE
Autocomplete it doesn't autocomplete

### ISSUE THREAD

**Issue by code56** [homonecloco/expvip-web#15]

**Comment by code56** [comment]
Look at line:
https://github.com/homonecloco/expvip-web/blob/master/app/controllers/genes_controller.rb#L92

**Comment by code56** [comment]
To debug this pls add a line where it would run something like this: 
   if the user didn't explicitly select the Gene set from the dropdown menu ('Gene set'), 
    then: 
      use as default the (e.g. TGAC1 gene set) and then the autocomplete functionality (of autosuggesting gene names) will work.

**Comment by homonecloco** [comment]
I believe this is fixed.
