### ISSUE TITLE
TGACv1 dataset on Blast gives errors

### ISSUE THREAD

**Issue by Bijan-Ghasemi-Afshar** [homonecloco/expvip-web#32]

**Comment by homonecloco** [comment]
This was fixed. The error was a corrupted blast database. This was because the input file has tabs and the version of makeblastdb in the server doesn't support names with tabs. It was fixed by ```sed -i -e 's/\t/     /g' Triticum_aestivum_CS42_TGACv1_scaffold.annotation.gff3.cdna.fa```.
