### ISSUE TITLE
Reduce the name lengths

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/expvip-web#36]
If you are saving more than 3 genes, instead of saving the name as ```gene1_gene2_gene3_gene4_tpm.csv```, save the name as ```heatmap_DATE_tpm.csv```

@sophie-harrington does it make sense?

**Comment by sophie-harrington** [comment]
That sounds fine! Thanks guys 😊

**Comment by Bijan-Ghasemi-Afshar** [comment]
Done!
