### ISSUE TITLE
my data cannot be loaded.

### ISSUE THREAD

**Issue by L-jia** [homonecloco/expvip-web#55]
when I put some gene IDs to search database, it says data cannot be loaded.How can I salve this problem

**Comment by L-jia** [comment]
when I use example ID to search database,it also show data couldn't be loaded

**Comment by homonecloco** [comment]
Hi, 
Can you please describe better your issue? Are you trying to do something in www.wheat-expression.com? Or are you trying to load your data on your own installation? If you could have some screenshoots or examples where you are facing the problem it would help us to figure out what is the issue. 
Best, 
Ricardo.

**Comment by L-jia** [comment]
Thanks. I also want to know which country you are. I don't know if people from other regions or countries are experiencing the same situation. Is this question related to the regional network?

**Comment by homonecloco** [comment]
I think it is in our side. I had the same issue. We are based in the UK.

**Comment by homonecloco** [comment]
Hi again, 
There was a problem in the server, which I think I fixed. Please try again and let me know if there is any issue with it.
Best, 
Ricardo.
